### ISSUE TITLE
Crashes when "Download Async" is deselected.

### ISSUE THREAD

**Issue by Daltz333** [JamieSinn/CSA-USB-Tool#11]
I get a "Unable to establish SSL/TLS Connection" uncaught exception when unticking the box and then pressing download.

**Comment by JamieSinn** [comment]
That's an interesting one, let me look into that

**Comment by JamieSinn** [comment]
Seems like this is a user sided issue, I can't replicate this as much as I try.
If you have reproduction steps, please re-open a new issue.
