### ISSUE TITLE
Fails to download VSCode and WPILib files

### ISSUE THREAD

**Issue by Daltz333** [JamieSinn/CSA-USB-Tool#12]
The tool fails to download the WPILib installer and VSCode files. The downloading software box is completely full and just stuck there. And the files are labelled as "0 KBs"

OS: Windows 10 Pro 64bit 17134.523

![file1](https://i.ibb.co/pj2QC0k/48.png)

![file2](https://i.ibb.co/xCRKtVH/49.png)

**Comment by JamieSinn** [comment]
Known issue, working on finding a solution. Stay tuned.

**Comment by JamieSinn** [comment]
Seems to be something related to their size and the size header not being sent.
Gonna see if I can workaround.
