### ISSUE TITLE
Add .NET framework to 2019 list?

### ISSUE THREAD

**Issue by fovea1959** [JamieSinn/CSA-USB-Tool#18]
Per http://wpilib.screenstepslive.com/s/currentCS/m/getting_started/l/999999-installing-c-and-java-development-tools-for-frc, we may want to make sure we grab copies of the .NET runtime?

https://support.microsoft.com/en-us/help/3151800/the-net-framework-4-6-2-offline-installer-for-windows

**Comment by JamieSinn** [comment]
Dotnet is an interesting peril. I'm not sure how the licensing/accepting their EULA works when I give a direct download.
I'll look into this, but it's definitely a good idea.
