### ISSUE TITLE
Change LabVIEW to offline installers

### ISSUE THREAD

**Issue by aballard-mars** [JamieSinn/CSA-USB-Tool#37]
I like the tool and used it a lot last year. I see there are a number of changes already started for this year. I'm working with the beta since it looks like you've changed some file names to work with FTC that broke backward compatibility to last year's tool. I figured if I was going to have to work with source I might as well work with the new stuff. I like that you can pick items to include from a list, but I'd suggest switching LabVIEW from the online installer to the offline installer.

**Comment by JamieSinn** [comment]
Good idea, I'll add that to my todo list.
