### ISSUE TITLE
Allow custom CSV's to be used for download list

### ISSUE THREAD

**Issue by fovea1959** [JamieSinn/CSA-USB-Tool#4]
Consider somehow letting me specify the path/URL to my own CSV of what to load?

**Comment by JamieSinn** [comment]
As long as it follows the same format, I could potentially do this with a commandline arg. 
What reason would it be used for?

**Comment by Simpsonboy77** [comment]
I could see some value in not wanting to download the labview image, as a CSA has access to the original discs in spare parts. Additionally the image is large, sometimes you may not have a fast download speed (especially if you are doing an event from a hotel).

**Comment by JamieSinn** [comment]
Good point, will add a new release that allows a path to a different CSV to be downloaded

**Comment by fovea1959** [comment]
Some use cases: I keep 64 bit versions of the Java pieces around, I want additional manuals besides the C programming manual, 64-bit silverlight.....

**Comment by JamieSinn** [comment]
Feel free to make a pr adding new software CSVs, always welcome new additions. Should be ready tonight

**Comment by JamieSinn** [comment]
https://github.com/JamieSinn/CSA-USB-Tool/commit/8bb6e2f702769e229c3e87db3d7af61204dd622c

Above commit adds the functionality, will be pushing a release sometime soon.

**Comment by JamieSinn** [comment]
https://github.com/JamieSinn/CSA-USB-Tool/releases/tag/2018.3
