### ISSUE TITLE
Tool doesn't start

### ISSUE THREAD

**Issue by sciencewhiz** [JamieSinn/CSA-USB-Tool#44]
The CSA USB Tool doesn't start and gives the following traceback with the beta version

`
Unhandled Exception: System.UriFormatException: Invalid URI: The format of the U RI could not be determined.                                                         at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)        at System.Uri..ctor(String uriString)                                            at CSAUSBTool.FrcSeason.GetWebList(String uri)                                   at CSAUSBTool.CSAUSBTool..ctor(IReadOnlyList 1 args)                             at CSAUSBTool.Program.Main(String[] args)
`

With the last release version I get this traceback:

`
Unhandled Exception: System.Net.WebException: The remote server returned an erro r: (404) Not Found.                                                                 at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request )                                                                                   at System.Net.WebClient.DownloadString(Uri address)                              at CSAUSBTool.FRCYear.GetWebList(String uri)                                     at CSAUSBTool.FRCYear.GetWebList(Int32 year)                                     at CSAUSBTool.CSAUSBTool..ctor(String[] args)                                    at CSAUSBTool.Program.Main(String[] args)
`

**Comment by JamieSinn** [comment]
Yeah, I'll be fixing this later today. Just gotta finish some other projects

**Comment by JamieSinn** [comment]
https://github.com/JamieSinn/CSA-USB-Tool/releases/tag/2020v1
