### ISSUE TITLE
Windows Defender treats the tool as unwanted software

### ISSUE THREAD

**Issue by Modelmat** [JamieSinn/CSA-USB-Tool#49]
![image](https://user-images.githubusercontent.com/25718989/93421221-179b8c00-f8f4-11ea-808b-7328aa3aa4d1.png)

I'm not sure what can actually be done to get Windows to not do this, but Windows Defender quarantines the tool upon downloading it.

**Comment by fletch3555** [comment]
What can be done? Code-signing.  But that's expensive (last I checked... but it's been a while).  Not sure what other options might exist though

**Comment by JamieSinn** [comment]
I'll eventually get a CSS but for now you just have to bypass it unfortunately.

**Comment by JamieSinn** [comment]
Looks like the EV cert I'd need is $300 USD/yr, minimum. 

I don't have the cash on hand for that, but I'll look at getting an OV cert later.

**Comment by JamieSinn** [comment]
https://i.imgur.com/xljUaBa.png

@fletch3555 
@Modelmat 

Coming soon to a release near you!

**Comment by fletch3555** [comment]
*chef kiss*

**Comment by JamieSinn** [comment]
https://i.imgur.com/aHeSSeD.png - Seems like on a computer that it hasn't seen the release before - this will show up once.
