### ISSUE TITLE
Rev Software is 2020

### ISSUE THREAD

**Issue by sciencewhiz** [JamieSinn/CSA-USB-Tool#54]

**Comment by JamieSinn** [comment]
Rev themselves update the software. Unfortunately still waiting on them.

**Comment by willtoth** [comment]
@NoahAndrews

**Comment by NoahAndrews** [comment]
Thanks for the ping @willtoth. I've been working on getting the REV Hardware Client capable of working offline in a way that will be useful with this tool, but support got in the way last week.
