### ISSUE TITLE
Add Limelight USB Drivers

### ISSUE THREAD

**Issue by hendjoshsr71** [JamieSinn/CSA-USB-Tool#65]
New CSA here (new to FRC as well) Great tool BTW!

It would be useful to include the USB Driver Tool on this page: [here](https://limelightvision.io/pages/downloads)

And maybe a link too to the "How to" for Limelight:  [link](https://docs.limelightvision.io/en/latest/getting_started.html#imaging)

And maybe throw the Limelight files all in a folder too?

**Comment by JamieSinn** [comment]
Ideally we try to avoid manually packaging anything, and only take direct downloads from the manufacturer.
Reasons mostly surround efficiency and update speed.

**Comment by hendjoshsr71** [comment]
Sorry. I accidentally copied and pasted the same website link to both of my links above. 

Here is the page from the Limelight, https://limelightvision.io/pages/downloads see USB Drivers, which redirects to here https://github.com/raspberrypi/usbboot/raw/master/win32/rpiboot_setup.exe

Perhaps that redirect is the basis of your comment, "avoid manually packaging anything"? 

But without that driver your out of luck till you can find some useable internet.

**Comment by JamieSinn** [comment]
I was more referring to the comment below.
> And maybe throw the Limelight files all in a folder too?

The driver files would be a good addition - feel free to make a PR - the CSV format should be pretty self explanatory.
