### ISSUE TITLE
NI_FRC2018 zip file corrupted in ISO

### ISSUE THREAD

**Issue by sciencewhiz** [JamieSinn/CSA-USB-Tool#8]
After creating flash drives, I noticed that the NI_FRC2018.zip was only 1gb, not 5gb. Looking in the downloaded data, it was 5gb, as shown.
![image](https://user-images.githubusercontent.com/4885091/37193374-650378c6-231e-11e8-878c-34bd609a97c8.png)
However, when mounting the iso, it is only 1gb, as shown.
![image](https://user-images.githubusercontent.com/4885091/37193563-58f98c40-231f-11e8-8934-66a501f1ac7a.png)
The smaller file doesn't open because it's not a valid zip file

**Comment by JamieSinn** [comment]
That doesn't make sense.... 

Are you sure you're not aborting as soon as you see the ISO? It takes a little bit to finish building it because of LV

Can you record/reproduce this?

**Comment by sciencewhiz** [comment]
What do you mean by record. Will try again tomorrow. It feels like a 4gb+ thing.

**Comment by JamieSinn** [comment]
GIF or WEBM recording.

I'm not sure why 4G would come into play, as there's no FAT formatting on the .iso file.

**Comment by JamieSinn** [comment]
Hmm, I just confirmed this myself.
That's very odd...
I'll take a look at it and see if I can find out why this is happening.

**Comment by sciencewhiz** [comment]
According to Wikipedia, iso9660 only supports 4gb files, unless extensions are used.

**Comment by JamieSinn** [comment]
And that would do it!

I'll see if the library can support other ISO systems, or I'll just exclude the LV zip from the ISO.

**Comment by JamieSinn** [comment]
Looks like I'll just have to exclude it from the ISO. 
I don't really want to implement ISO creation when it's not a huge thing for everyone.
