### ISSUE TITLE
VS Code for 2023

### ISSUE THREAD

**Issue by 132ikl** [JamieSinn/CSA-USB-Tool#87]
It looks like in previous years VS Code was included, but it's not this year. I believe you still need it in order to install VS Code using the WPILib installer, since they can't redistribute VS Code (this may also complicate #52)

**Comment by sciencewhiz** [comment]
The previous VS Code in this tool was not really correct, it wasn't usable by the installer. 

See wpilibsuite/WPILibInstaller-Avalonia#335 for possible changes to the installer that would make this much easier to support.

**Comment by 132ikl** [comment]
Based on Thad's comment in #355, it seems like once that change is made it will be possible for CSA-USB-Tool to just download the stock VS Code zip like before.

**Comment by JamieSinn** [comment]
that'd be lovely - Here's hoping
